version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: mix phx.server
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  postgres:
    driver: local
